"""empty message

Revision ID: bcc2b193de63
Revises: bce8e8c2879f
Create Date: 2021-03-22 23:16:14.694139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcc2b193de63'
down_revision = 'bce8e8c2879f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('link_to_facebook', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('link_to_google', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'link_to_google')
    op.drop_column('users', 'link_to_facebook')
    # ### end Alembic commands ###
